Repository squanchy-dev/squanchy-android, pull requests merged in 2018-04, with the labels that each got.

#499 Use proper checksum for track ID
  app/src/debug/java/net/squanchy/support/debug/DebugActivity.kt
  app/src/main/java/net/squanchy/notification/NotificationCreator.kt
  app/src/main/java/net/squanchy/schedule/domain/view/Track.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/ScheduleTracksFilter.kt
  app/src/main/java/net/squanchy/service/firebase/FirestoreMappers.kt
  app/src/main/java/net/squanchy/service/repository/firestore/FirestoreTracksRepository.kt
  app/src/main/java/net/squanchy/service/repository/injection/RepositoryModule.kt
  app/src/main/java/net/squanchy/signin/SignInComponent.kt
  app/src/test/java/net/squanchy/schedule/domain/view/ScheduleFixtures.kt
  app/src/test/java/net/squanchy/service/firebase/FirestoreEventMapperTest.kt
  app/src/test/java/net/squanchy/service/firebase/FirestoreTrackMapperTest.kt
  app/src/test/java/net/squanchy/service/firebase/model/schedule/FirestoreTracksRepositoryTest.kt
Labels: techdebt

#501 Update oss licences
  app/src/main/java/net/squanchy/about/licenses/Libraries.kt
  app/src/main/java/net/squanchy/about/licenses/License.kt
  app/src/main/res/values/licenses.xml
Labels: techdebt

#502 Improve filters UI/Animate filters in out
  app/src/main/java/net/squanchy/SquanchyApplication.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/CheckableTrack.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/ScheduleTracksFilter.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/TracksFilterAdapter.kt
  app/src/main/java/net/squanchy/support/view/RecyclerViewUtils.kt
  app/src/main/res/layout/activity_track_filters.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/styles.xml
Labels: UI/UX polish

#504 Use list adapters where possible (part 1)
  app/src/main/java/net/squanchy/schedule/tracksfilter/TracksFilterAdapter.kt
  app/src/main/java/net/squanchy/schedule/view/EventsAdapter.kt
  app/src/main/java/net/squanchy/schedule/view/ScheduleDayPageView.kt
  app/src/main/java/net/squanchy/schedule/view/ScheduleViewPagerAdapter.kt
  app/src/main/java/net/squanchy/search/view/SearchRecyclerView.java
  app/src/main/java/net/squanchy/tweets/TweetsPageView.kt
  app/src/main/java/net/squanchy/tweets/view/TweetsAdapter.kt
Labels: techdebt, under the hood

#500 Search ui
  app/src/main/java/net/squanchy/search/SearchActivity.java
  app/src/main/java/net/squanchy/search/SearchActivity.kt
  app/src/main/java/net/squanchy/search/SearchResult.kt
  app/src/main/java/net/squanchy/search/SearchService.kt
  app/src/main/java/net/squanchy/search/algolia/AlgoliaSearchEngine.kt
  app/src/main/java/net/squanchy/search/view/ItemsAdapter.java
  app/src/main/java/net/squanchy/search/view/SearchAdapter.java
  app/src/main/java/net/squanchy/search/view/SearchRecyclerView.java
  app/src/main/res/drawable/ic_cloud_off.xml
  app/src/main/res/drawable/ic_error_outline.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/net/squanchy/search/SearchServiceTest.kt
  app/src/test/java/net/squanchy/search/algolia/AlgoliaSearchEngineTest.kt
  app/src/test/java/net/squanchy/search/view/ItemsAdapterTest.kt
  app/src/test/java/net/squanchy/speaker/domain/view/SpeakerFixtures.kt
Labels: UI/UX polish, epic:firestore

#506 Tweets empty state
  app/src/main/java/net/squanchy/tweets/TweetsPageView.kt
  app/src/main/res/drawable/ic_twitter_empty.xml
  app/src/main/res/layout/view_page_tweets.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/palette.xml
  app/src/main/res/values/styles.xml
Labels: UI/UX polish

#505 Use list adapters for favourites
  app/src/main/java/net/squanchy/favorites/FavoritesComponent.kt
  app/src/main/java/net/squanchy/favorites/FavoritesModule.kt
  app/src/main/java/net/squanchy/favorites/FavoritesPageView.kt
  app/src/main/java/net/squanchy/favorites/FavoritesService.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesAdapter.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesItem.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesListView.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesViewHolders.kt
  app/src/main/java/net/squanchy/schedule/ScheduleService.kt
  app/src/main/java/net/squanchy/schedule/view/EventsAdapter.kt
  app/src/main/java/net/squanchy/search/view/SearchAdapter.java
  app/src/test/java/net/squanchy/favorites/FirestoreFavoritesServiceTest.kt
  app/src/test/java/net/squanchy/favorites/ListItemFixtures.kt
Labels: techdebt, under the hood

#507 Improve favourites empty state
  app/src/main/res/drawable/empty_favorites_signed_out.xml
  app/src/main/res/drawable/ic_favorites_empty_not_signed_in.xml
  app/src/main/res/layout/view_page_favorites.xml
  app/src/main/res/values/dimens.xml
Labels: UI/UX polish

#509 Move borrowed code out
  app/build.gradle
  build.gradle
  dependencies.gradle
  renderthread/build.gradle
  renderthread/src/main/AndroidManifest.xml
  renderthread/src/main/java/me/eugeniomarletti/renderthread/CanvasProperty.java
  renderthread/src/main/java/me/eugeniomarletti/renderthread/CanvasUtils.java
  renderthread/src/main/java/me/eugeniomarletti/renderthread/HardwareCanvasProperty.java
  renderthread/src/main/java/me/eugeniomarletti/renderthread/RenderThread.java
  renderthread/src/main/java/me/eugeniomarletti/renderthread/RenderThreadDelegate.java
  renderthread/src/main/java/me/eugeniomarletti/renderthread/RenderThreadDelegateHw.java
  renderthread/src/main/java/me/eugeniomarletti/renderthread/RenderThreadMethods.java
  renderthread/src/main/java/me/eugeniomarletti/renderthread/SoftwareCanvasProperty.java
  renderthread/src/main/java/me/eugeniomarletti/renderthread/typeannotation/CanvasProperty.java
  renderthread/src/main/java/me/eugeniomarletti/renderthread/typeannotation/DisplayListCanvas.java
  renderthread/src/main/java/me/eugeniomarletti/renderthread/typeannotation/RenderNodeAnimator.java
  renderthread/src/main/res/values/strings.xml
  settings.gradle
  team-props/ktlint.gradle
  team-props/static-analysis/checkstyle-suppressions.xml
  team-props/static-analysis/findbugs-excludes.xml
  team-props/static-analysis/pmd-rules.xml
Labels: devops, techdebt

#513 Fix timezones not being applied at LocalDateTime/LocalDate creation
  app/src/main/java/net/squanchy/schedule/ScheduleService.kt
  app/src/main/java/net/squanchy/service/firebase/FirestoreMappers.kt
  app/src/test/java/net/squanchy/TestDateTimeConstants.kt
  app/src/test/java/net/squanchy/schedule/FirestoreScheduleServiceTest.kt
  app/src/test/java/net/squanchy/schedule/domain/view/ScheduleFixtures.kt
  app/src/test/java/net/squanchy/service/firebase/FirestoreEventMapperTest.kt
  app/src/test/java/net/squanchy/service/firebase/FirestoreFixtures.kt
Labels: bug

#514 Track notification status
  app/src/main/java/net/squanchy/SquanchyApplication.kt
  app/src/main/java/net/squanchy/analytics/Analytics.kt
  app/src/main/java/net/squanchy/analytics/FirstStartDetector.kt
  app/src/main/java/net/squanchy/settings/SettingsFragment.kt
Labels: epic:analytics

#521 Update sample config files
  team-props/application.properties.sample
  team-props/releaseSigningConfig.properties.sample
  team-props/secrets.properties.sample
Labels: devops

#522 Fix notifications speakers
  app/src/debug/java/net/squanchy/support/debug/DebugActivity.kt
  app/src/main/java/net/squanchy/notification/NotificationCreator.kt
Labels: bug

#525 Share the RecyclerView pool of the schedule pages
  app/src/main/java/net/squanchy/schedule/view/ScheduleViewPagerAdapter.kt
Labels: under the hood

#526 Show event room in schedule
  app/src/debug/java/net/squanchy/support/debug/DebugActivity.kt
  app/src/main/java/net/squanchy/favorites/FavoritesPageView.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesViewHolders.kt
  app/src/main/java/net/squanchy/imageloader/ImageLoaderComponent.kt
  app/src/main/java/net/squanchy/injection/ApplicationComponent.kt
  app/src/main/java/net/squanchy/remoteconfig/FeatureFlags.kt
  app/src/main/java/net/squanchy/remoteconfig/RemoteConfig.kt
  app/src/main/java/net/squanchy/remoteconfig/RemoteConfigModule.kt
  app/src/main/java/net/squanchy/schedule/ScheduleComponent.kt
  app/src/main/java/net/squanchy/schedule/SchedulePageView.kt
  app/src/main/java/net/squanchy/schedule/ScheduleService.kt
  app/src/main/java/net/squanchy/schedule/domain/view/Place.kt
  app/src/main/java/net/squanchy/schedule/view/EventItemView.kt
  app/src/main/java/net/squanchy/schedule/view/EventViewHolder.kt
  app/src/main/java/net/squanchy/schedule/view/EventsAdapter.kt
  app/src/main/java/net/squanchy/schedule/view/OtherEventItemView.kt
  app/src/main/java/net/squanchy/schedule/view/ScheduleDayPageView.kt
  app/src/main/java/net/squanchy/schedule/view/ScheduleViewPagerAdapter.kt
  app/src/main/java/net/squanchy/schedule/view/TalkEventItemView.kt
  app/src/main/java/net/squanchy/search/view/SearchRecyclerView.kt
  app/src/main/java/net/squanchy/service/firebase/FirestoreMappers.kt
  app/src/main/java/net/squanchy/service/firebase/model/schedule/FirestoreSchedule.kt
  app/src/main/java/net/squanchy/settings/view/SettingsHeaderLayout.kt
  app/src/main/java/net/squanchy/speaker/widget/SpeakerHeaderView.kt
  app/src/main/java/net/squanchy/support/ContextUnwrapper.kt
  app/src/main/java/net/squanchy/support/widget/SpeakerView.kt
  app/src/main/java/net/squanchy/tweets/TweetsPageView.kt
  app/src/main/java/net/squanchy/tweets/view/TweetFooterView.kt
  app/src/main/java/net/squanchy/tweets/view/TweetItemView.kt
  app/src/main/java/net/squanchy/venue/VenueInfoPageView.kt
  app/src/main/res/layout/item_schedule_event_talk.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/remote_config_defaults.xml
  app/src/test/java/net/squanchy/schedule/domain/view/ScheduleFixtures.kt
  app/src/test/java/net/squanchy/service/firebase/FirestoreFixtures.kt
Labels: UI/UX polish

#530 Update Android Gradle Plugin 3.1.0 -> 3.1.1
  dependencies.gradle
Labels: devops

#532 Fix search crashing — hotfix
  app/src/main/java/net/squanchy/search/SearchActivity.kt
  app/src/main/java/net/squanchy/search/SearchService.kt
  app/src/main/java/net/squanchy/search/view/SearchRecyclerView.kt
Labels: bug

#533 Fix a crash in the SearchActivity and improve its state management
  app/src/main/java/net/squanchy/search/SearchActivity.kt
  app/src/main/java/net/squanchy/search/SearchService.kt
  app/src/main/java/net/squanchy/search/view/GridSpanSizeLookup.kt
  app/src/main/java/net/squanchy/search/view/SearchAdapter.kt
Labels: bug

#534 Search UI tweaks
  app/src/main/java/net/squanchy/imageloader/GlideImageLoader.kt
  app/src/main/java/net/squanchy/imageloader/ImageLoader.kt
  app/src/main/java/net/squanchy/schedule/view/EventItemView.kt
  app/src/main/java/net/squanchy/schedule/view/OtherEventItemView.kt
  app/src/main/java/net/squanchy/schedule/view/TalkEventItemView.kt
  app/src/main/java/net/squanchy/search/SearchActivity.kt
  app/src/main/java/net/squanchy/search/SearchItemView.kt
  app/src/main/java/net/squanchy/search/view/SearchAdapter.kt
  app/src/main/java/net/squanchy/search/view/SearchItemViewHolder.kt
  app/src/main/java/net/squanchy/search/view/SearchRecyclerView.kt
  app/src/main/java/net/squanchy/support/widget/SpeakerView.kt
  app/src/main/res/drawable/ic_avatar_placeholder.xml
  app/src/main/res/values-w450dp/integers.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/styles.xml
Labels: UI/UX polish

#535 Fix proguard config
  app/build.gradle
  app/proguard-rules.pro
  dependencies.gradle
  renderthread/build.gradle
  renderthread/src/main/java/me/eugeniomarletti/renderthread/RenderThreadDelegate.java
Labels: bug

#539 Add @IgnoreExtraProperties to FirestoreEvent and FirestoreDay
  app/src/main/java/net/squanchy/service/firebase/model/schedule/FirestoreSchedule.kt
Labels: devops

#540 Ensure circular reveal maintains end colour when on SW rendering (P+)
  app/src/main/java/net/squanchy/support/graphics/CircularRevealDrawable.kt
Labels: bug

#541 Fix voice search crash on Samsung
  app/src/main/java/net/squanchy/search/SearchActivity.kt
  app/src/main/java/net/squanchy/signin/SignInActivity.kt
Labels: bug

#538 Fix text cut in Speaker Details when scrollable
  app/src/main/java/net/squanchy/speaker/widget/SpeakerDetailsLayout.kt
  app/src/main/java/net/squanchy/speaker/widget/SpeakerHeaderView.kt
  app/src/main/res/layout/activity_speaker_details.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: bug

#543 Use timezone when formatting non-session event times
  app/src/main/java/net/squanchy/schedule/view/OtherEventItemView.kt
Labels: bug, ⚠️BLOCKER ⚠️

#529 Wifi configuration
  app/src/main/AndroidManifest.xml
  app/src/main/java/net/squanchy/navigation/Navigator.kt
  app/src/main/java/net/squanchy/remoteconfig/FeatureFlags.kt
  app/src/main/java/net/squanchy/remoteconfig/RemoteConfig.kt
  app/src/main/java/net/squanchy/remoteconfig/WifiConfiguration.kt
  app/src/main/java/net/squanchy/settings/SettingsFragment.kt
  app/src/main/java/net/squanchy/settings/SettingsFragmentComponent.kt
  app/src/main/java/net/squanchy/settings/WifiConfigErrorActivity.kt
  app/src/main/java/net/squanchy/settings/WifiConfigErrorActivityComponent.kt
  app/src/main/java/net/squanchy/wificonfig/WifiConfigModule.kt
  app/src/main/java/net/squanchy/wificonfig/WifiConfigService.kt
  app/src/main/res/drawable/ic_wifi.xml
  app/src/main/res/drawable/ic_wifi_error.xml
  app/src/main/res/layout/activity_wifi_config_error.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/palette.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/settings_preferences.xml
Labels: new feature

#546 Add default value for the Wifi remote config feature flag
  app/src/main/res/xml/remote_config_defaults.xml
Labels: under the hood

#547 Wifi config analytics
  app/src/main/java/net/squanchy/analytics/Analytics.kt
  app/src/main/java/net/squanchy/settings/SettingsFragment.kt
  app/src/main/java/net/squanchy/wificonfig/SignInOrigin.kt
  app/src/main/java/net/squanchy/wificonfig/WifiConfigModule.kt
  app/src/main/java/net/squanchy/wificonfig/WifiConfigService.kt
Labels: epic:analytics

#548 Tweak copy: "wifi" -> "Wi-Fi"
  app/src/main/res/values/strings.xml
Labels: UI/UX polish

#553 Update OSS licences, cleanup resources
  app/build.gradle
  app/src/main/java/net/squanchy/about/licenses/Libraries.kt
  app/src/main/java/net/squanchy/about/licenses/License.kt
  app/src/main/res/drawable/ic_contest_beacon.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_trophy.xml
  app/src/main/res/values/licenses.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: techdebt

#554 SQ-549/Add RxLint, fix all outstanding issues
  app/build.gradle
  app/src/main/java/net/squanchy/about/licenses/Libraries.kt
  app/src/main/java/net/squanchy/eventdetails/EventDetailsActivity.kt
  app/src/main/java/net/squanchy/favorites/FavoritesPageView.kt
  app/src/main/java/net/squanchy/onboarding/account/AccountOnboardingActivity.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/ScheduleTracksFilter.kt
  app/src/main/java/net/squanchy/search/SearchActivity.kt
  app/src/main/java/net/squanchy/settings/SettingsFragment.kt
  app/src/main/java/net/squanchy/signin/SignInActivity.kt
  app/src/main/java/net/squanchy/venue/VenueInfoPageView.kt
  dependencies.gradle
Labels: bug

#558 Convert Favourites to Constraint layout
  app/src/main/java/net/squanchy/favorites/FavoritesPageView.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesSignedInEmptyLayout.kt
  app/src/main/res/layout/merge_no_favorites_view.xml
  app/src/main/res/layout/view_page_favorites.xml
  dependencies.gradle
Labels: techdebt, ⚠️BLOCKER ⚠️

#559 Add favourites in schedule
  app/src/debug/java/net/squanchy/support/debug/DebugActivity.kt
  app/src/main/java/net/squanchy/eventdetails/EventDetailsService.kt
  app/src/main/java/net/squanchy/eventdetails/widget/EventDetailsCoordinatorLayout.kt
  app/src/main/java/net/squanchy/favorites/FavoritesComponent.kt
  app/src/main/java/net/squanchy/favorites/FavoritesPageView.kt
  app/src/main/java/net/squanchy/favorites/FavoritesService.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesAdapter.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesListView.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesViewHolders.kt
  app/src/main/java/net/squanchy/notification/NotificationService.kt
  app/src/main/java/net/squanchy/schedule/SchedulePageView.kt
  app/src/main/java/net/squanchy/schedule/ScheduleService.kt
  app/src/main/java/net/squanchy/schedule/domain/view/Event.kt
  app/src/main/java/net/squanchy/schedule/view/EventItemView.kt
  app/src/main/java/net/squanchy/schedule/view/OtherEventItemView.kt
  app/src/main/java/net/squanchy/schedule/view/TalkEventItemView.kt
  app/src/main/java/net/squanchy/service/firebase/FirestoreMappers.kt
  app/src/main/res/drawable/ic_avatar_placeholder.xml
  app/src/main/res/layout/item_schedule_event_talk.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/net/squanchy/FakeAuthService.kt
  app/src/test/java/net/squanchy/favorites/FirestoreFavoritesServiceTest.kt
  app/src/test/java/net/squanchy/schedule/FirestoreScheduleServiceTest.kt
  app/src/test/java/net/squanchy/schedule/domain/view/ScheduleFixtures.kt
  app/src/test/java/net/squanchy/search/SearchServiceTest.kt
  app/src/test/java/net/squanchy/service/firebase/FirestoreFixtures.kt
Labels: new feature, techdebt

#560 Convert EventDetails to ConstraintLayout, fix timezones, allow workshops as favourites
  app/src/main/java/net/squanchy/eventdetails/widget/EventDetailsCoordinatorLayout.kt
  app/src/main/java/net/squanchy/eventdetails/widget/EventDetailsHeaderLayout.kt
  app/src/main/java/net/squanchy/eventdetails/widget/EventDetailsLayout.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesSignedInEmptyLayout.kt
  app/src/main/java/net/squanchy/home/HomeActivity.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/ScheduleTracksFilter.kt
  app/src/main/java/net/squanchy/signin/SignInActivity.kt
  app/src/main/java/net/squanchy/speaker/widget/SpeakerDetailsLayout.kt
  app/src/main/java/net/squanchy/speaker/widget/SpeakerHeaderView.kt
  app/src/main/java/net/squanchy/support/text/Html.kt
  app/src/main/java/net/squanchy/tweets/view/TweetItemView.kt
  app/src/main/java/net/squanchy/tweets/view/TweetUrlSpanFactory.kt
  app/src/main/java/net/squanchy/venue/VenueInfoPageView.kt
  app/src/main/res/layout/activity_event_details.xml
  app/src/main/res/layout/merge_event_details_layout.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: bug, techdebt

#561 Setting to show favourites in schedule
  app/src/main/java/net/squanchy/analytics/Analytics.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesAdapter.kt
  app/src/main/java/net/squanchy/schedule/SchedulePageView.kt
  app/src/main/java/net/squanchy/schedule/view/EventsAdapter.kt
  app/src/main/java/net/squanchy/schedule/view/ScheduleDayPageView.kt
  app/src/main/java/net/squanchy/schedule/view/ScheduleViewPagerAdapter.kt
  app/src/main/java/net/squanchy/settings/SettingsFragment.kt
  app/src/main/java/net/squanchy/settings/preferences/LocalPreferences.kt
  app/src/main/res/drawable/ic_favorite_settings.xml
  app/src/main/res/layout/view_page_schedule.xml
  app/src/main/res/values-en-rGB/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings_preferences.xml
Labels: UI/UX polish

#562 Highlight keynote in schedule
  app/src/main/java/net/squanchy/eventdetails/widget/EventDetailsLayout.kt
  app/src/main/java/net/squanchy/home/HomeActivity.kt
  app/src/main/java/net/squanchy/schedule/view/TalkEventItemView.kt
  app/src/main/java/net/squanchy/search/SearchItemView.kt
  app/src/main/java/net/squanchy/speaker/widget/SpeakerHeaderView.kt
  app/src/main/java/net/squanchy/support/content/res/Theme.kt
  app/src/main/java/net/squanchy/support/graphics/Color.kt
  app/src/main/java/net/squanchy/support/widget/SpeakerView.kt
  app/src/main/java/net/squanchy/tweets/view/TweetUrlSpanFactory.kt
  app/src/main/res/layout/activity_event_details.xml
  app/src/main/res/layout/activity_speaker_details.xml
  app/src/main/res/layout/item_schedule_event_talk.xml
  app/src/main/res/layout/item_search_result_small.xml
Labels: UI/UX polish

#564 Hide level in event details for keynotes
  app/src/main/java/net/squanchy/eventdetails/widget/EventDetailsLayout.kt
Labels: UI/UX polish

#566 Fix favourites icon in schedule after AVD changes broke them
  app/src/main/res/layout/item_schedule_event_talk.xml
Labels: bug

#565 Hide (empty) image for 'other' items in schedule
  app/src/main/java/net/squanchy/schedule/view/OtherEventItemView.kt
  app/src/main/res/layout/item_schedule_event_other.xml
  app/src/main/res/values/dimens.xml
Labels: UI/UX polish, bug

#567 Comment out stuff in the play closure to prevent accidental shipping
  app/build.gradle
Labels: devops

#570 fix two errors with rx
  app/src/main/java/net/squanchy/search/algolia/AlgoliaSearchEngine.kt
  app/src/main/java/net/squanchy/service/firebase/FirebaseAuthService.kt
  renderthread/src/main/res/values/strings.xml
Labels: bug
