Repository squanchy-dev/squanchy-android, pull requests merged in 2018-12, with the labels that each got.

#572 Fix the offline persistence in firestore
  app/src/main/java/net/squanchy/service/firebase/injection/FirestoreModule.kt
Labels: :x: do not merge

#603 Update dependencies, remove Firebase RTDB & Perf, remove SAP
  .circleci/config.yml
  app/build.gradle
  app/src/main/java/net/squanchy/SquanchyApplication.kt
  app/src/main/java/net/squanchy/settings/SettingsActivity.kt
  app/src/main/java/net/squanchy/settings/SettingsFragment.kt
  app/src/main/java/net/squanchy/tweets/TweetsPageView.kt
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/merge_no_favorites_view.xml
  build.gradle
  dependencies.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  team-props/git-hooks/pre-push.sh
  team-props/static-analysis.gradle
  team-props/static-analysis/detekt-config.yml
Labels: techdebt, under the hood

#605 SQ-601/Use Timestamps with Firestore instead of Dates
  app/src/main/java/net/squanchy/schedule/ScheduleService.kt
  app/src/main/java/net/squanchy/service/firebase/FirestoreMappers.kt
  app/src/main/java/net/squanchy/service/firebase/injection/FirestoreModule.kt
  app/src/main/java/net/squanchy/service/firebase/model/schedule/FirestoreSchedule.kt
  app/src/main/java/net/squanchy/service/firebase/model/twitter/FirestoreTwitter.kt
  app/src/main/java/net/squanchy/tweets/domain/view/TweetViewModel.kt
  app/src/main/java/net/squanchy/tweets/view/TwitterFooterFormatter.kt
  app/src/test/java/net/squanchy/schedule/FirestoreScheduleServiceTest.kt
  app/src/test/java/net/squanchy/service/firebase/FirestoreEventMapperTest.kt
  app/src/test/java/net/squanchy/service/firebase/FirestoreFixtures.kt
Labels: techdebt, under the hood, ⚠️BLOCKER ⚠️
