Repository squanchy-dev/squanchy-android, pull requests merged in 2018-03, with the labels that each got.

#457 SQ-455/Filtering: refactor all the things
  .idea/inspectionProfiles/Squanchy.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/net/squanchy/SquanchyApplication.kt
  app/src/main/java/net/squanchy/favorites/FavoritesComponent.kt
  app/src/main/java/net/squanchy/favorites/FavoritesPageView.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesAdapter.kt
  app/src/main/java/net/squanchy/injection/ApplicationComponent.kt
  app/src/main/java/net/squanchy/navigation/Navigator.kt
  app/src/main/java/net/squanchy/schedule/ScheduleComponent.kt
  app/src/main/java/net/squanchy/schedule/ScheduleModule.kt
  app/src/main/java/net/squanchy/schedule/SchedulePageView.kt
  app/src/main/java/net/squanchy/schedule/ScheduleService.kt
  app/src/main/java/net/squanchy/schedule/domain/view/Schedule.kt
  app/src/main/java/net/squanchy/schedule/filterschedule/FilterSchedule.kt
  app/src/main/java/net/squanchy/schedule/filterschedule/FilterScheduleComponent.kt
  app/src/main/java/net/squanchy/schedule/filterschedule/FilterScheduleDialog.kt
  app/src/main/java/net/squanchy/schedule/filterschedule/FilterScheduleModule.kt
  app/src/main/java/net/squanchy/schedule/filterschedule/FilterScheduleService.kt
  app/src/main/java/net/squanchy/schedule/filterschedule/TracksFilter.kt
  app/src/main/java/net/squanchy/schedule/filterschedule/TracksFilterComponent.kt
  app/src/main/java/net/squanchy/schedule/filterschedule/TracksFilterModule.kt
  app/src/main/java/net/squanchy/service/firestore/FirestoreDbService.kt
  app/src/main/java/net/squanchy/service/firestore/model/schedule/FirestoreSchedule.kt
  app/src/main/java/net/squanchy/service/repository/DaysRepository.kt
  app/src/main/java/net/squanchy/service/repository/FilterScheduleRepository.kt
  app/src/main/java/net/squanchy/service/repository/TracksRepository.kt
  app/src/main/java/net/squanchy/service/repository/firestore/FirestoreTracksRepository.kt
  app/src/main/java/net/squanchy/service/repository/injection/RepositoryModule.kt
  app/src/main/res/layout/activity_track_filters.xml
  app/src/main/res/layout/track_filters_item.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/net/squanchy/FilterScheduleServiceTest.kt
  app/src/test/java/net/squanchy/schedule/FirestoreScheduleServiceTest.kt
  app/src/test/java/net/squanchy/schedule/domain/view/EventFixtures.java
  app/src/test/java/net/squanchy/schedule/domain/view/PlaceFixtures.java
  app/src/test/java/net/squanchy/schedule/domain/view/ScheduleFixtures.kt
  app/src/test/java/net/squanchy/schedule/domain/view/TrackFixtures.java
  app/src/test/java/net/squanchy/search/engines/EventSearchEngineTest.java
  app/src/test/java/net/squanchy/search/engines/EventSearchEngineTest.kt
  app/src/test/java/net/squanchy/search/engines/SpeakerSearchEngineTest.java
  app/src/test/java/net/squanchy/search/engines/SpeakerSearchEngineTest.kt
  app/src/test/java/net/squanchy/search/view/ItemsAdapterTest.java
  app/src/test/java/net/squanchy/search/view/ItemsAdapterTest.kt
  app/src/test/java/net/squanchy/service/firestore/FirestoreFixtures.kt
  app/src/test/java/net/squanchy/service/firestore/FirestoreSpeakerMapperTest.kt
  app/src/test/java/net/squanchy/service/firestore/model/schedule/FirestoreTracksRepositoryTest.kt
  app/src/test/java/net/squanchy/service/repository/InMemoryTracksFilterTest.kt
  app/src/test/java/net/squanchy/speaker/domain/view/SpeakerFixtures.java
  app/src/test/java/net/squanchy/speaker/domain/view/SpeakerFixtures.kt
Labels: techdebt, under the hood

#458 SQ-455/Rename filtering package
  app/src/main/AndroidManifest.xml
  app/src/main/java/net/squanchy/injection/ApplicationComponent.kt
  app/src/main/java/net/squanchy/navigation/Navigator.kt
  app/src/main/java/net/squanchy/schedule/ScheduleComponent.kt
  app/src/main/java/net/squanchy/schedule/ScheduleModule.kt
  app/src/main/java/net/squanchy/schedule/ScheduleService.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/ScheduleTracksFilter.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/TracksFilter.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/TracksFilterComponent.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/TracksFilterModule.kt
  app/src/test/java/net/squanchy/schedule/FirestoreScheduleServiceTest.kt
  app/src/test/java/net/squanchy/service/repository/InMemoryTracksFilterTest.kt
Labels: under the hood

#456 SQ-455 Add filtering
  .idea/inspectionProfiles/Squanchy.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/net/squanchy/SquanchyApplication.kt
  app/src/main/java/net/squanchy/favorites/FavoritesComponent.kt
  app/src/main/java/net/squanchy/favorites/FavoritesPageView.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesAdapter.kt
  app/src/main/java/net/squanchy/injection/ApplicationComponent.kt
  app/src/main/java/net/squanchy/navigation/Navigator.kt
  app/src/main/java/net/squanchy/schedule/ScheduleComponent.kt
  app/src/main/java/net/squanchy/schedule/ScheduleModule.kt
  app/src/main/java/net/squanchy/schedule/SchedulePageView.kt
  app/src/main/java/net/squanchy/schedule/ScheduleService.kt
  app/src/main/java/net/squanchy/schedule/domain/view/Schedule.kt
  app/src/main/java/net/squanchy/schedule/domain/view/Track.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/ScheduleTracksFilter.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/TracksFilter.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/TracksFilterComponent.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/TracksFilterModule.kt
  app/src/main/java/net/squanchy/service/firestore/FirestoreDbService.kt
  app/src/main/java/net/squanchy/service/firestore/injection/FirestoreModule.kt
  app/src/main/java/net/squanchy/service/firestore/model/schedule/FirestoreSchedule.kt
  app/src/main/java/net/squanchy/service/repository/DaysRepository.kt
  app/src/main/java/net/squanchy/service/repository/TracksRepository.kt
  app/src/main/java/net/squanchy/service/repository/firebase/FirebaseDaysRepository.kt
  app/src/main/java/net/squanchy/service/repository/firestore/FirestoreTracksRepository.kt
  app/src/main/java/net/squanchy/service/repository/injection/RepositoryModule.kt
  app/src/main/res/drawable/ic_filter_list.xml
  app/src/main/res/layout/activity_track_filters.xml
  app/src/main/res/layout/track_filters_item.xml
  app/src/main/res/menu/homepage.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/net/squanchy/schedule/FirestoreScheduleServiceTest.kt
  app/src/test/java/net/squanchy/schedule/domain/view/EventFixtures.java
  app/src/test/java/net/squanchy/schedule/domain/view/PlaceFixtures.java
  app/src/test/java/net/squanchy/schedule/domain/view/ScheduleFixtures.kt
  app/src/test/java/net/squanchy/schedule/domain/view/TrackFixtures.java
  app/src/test/java/net/squanchy/search/engines/EventSearchEngineTest.java
  app/src/test/java/net/squanchy/search/engines/EventSearchEngineTest.kt
  app/src/test/java/net/squanchy/search/engines/SpeakerSearchEngineTest.java
  app/src/test/java/net/squanchy/search/engines/SpeakerSearchEngineTest.kt
  app/src/test/java/net/squanchy/search/view/ItemsAdapterTest.java
  app/src/test/java/net/squanchy/search/view/ItemsAdapterTest.kt
  app/src/test/java/net/squanchy/service/firestore/FirestoreFixtures.kt
  app/src/test/java/net/squanchy/service/firestore/FirestoreSpeakerMapperTest.kt
  app/src/test/java/net/squanchy/service/firestore/model/schedule/FirestoreTracksRepositoryTest.kt
  app/src/test/java/net/squanchy/service/repository/InMemoryTracksFilterTest.kt
  app/src/test/java/net/squanchy/speaker/domain/view/SpeakerFixtures.java
  app/src/test/java/net/squanchy/speaker/domain/view/SpeakerFixtures.kt
Labels: UI/UX polish, new feature

#465 Update Ktlint again
  dependencies.gradle
Labels: under the hood

#468 Fix and update build properties plugin
  .circleci/config.yml
  .gitignore
  README.md
  app/build-properties.gradle
  app/build.gradle
  dependencies.gradle
  docs/setup.md
  team-props/application.properties.sample
  team-props/debugSigningConfig.properties
  team-props/releaseSigningConfig.properties.sample
  team-props/secrets.properties.sample
  team-props/signing/debug.keystore
Labels: devops, techdebt

#467 Fest to Truth
  app/build.gradle
  app/src/test/java/net/squanchy/search/engines/EventSearchEngineTest.java
  app/src/test/java/net/squanchy/search/engines/SpeakerSearchEngineTest.java
  app/src/test/java/net/squanchy/search/view/ItemsAdapterTest.java
  dependencies.gradle
Labels: devops

#470 Update Gradle 4.5 -> 4.6
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: devops

#471 Add badges to README
  README.md
Labels: devops

#472 Firestore track view
  app/src/main/java/net/squanchy/service/firestore/FirestoreDbService.kt
  app/src/main/java/net/squanchy/service/firestore/model/schedule/FirestoreSchedule.kt
Labels: epic:firestore

#474 Hotfix Firestore implementation
  app/src/main/java/net/squanchy/favorites/view/FavoritesAdapter.kt
  app/src/main/java/net/squanchy/favorites/view/FavoritesListView.kt
  app/src/main/java/net/squanchy/schedule/domain/view/Event.kt
  app/src/main/java/net/squanchy/schedule/view/EventsAdapter.kt
  app/src/main/java/net/squanchy/schedule/view/TalkEventItemView.kt
  app/src/main/java/net/squanchy/service/firestore/FirestoreDbService.kt
  app/src/main/java/net/squanchy/tweets/service/TwitterService.kt
Labels: epic:firestore

#481 Reformat code after updating dependencies
  app/src/main/java/net/squanchy/schedule/view/OtherEventItemView.kt
  app/src/main/java/net/squanchy/service/firebase/FirestoreMappers.kt
  app/src/main/java/net/squanchy/support/view/CardSpacingItemDecorator.kt
  team-props/git-hooks/pre-commit.sh
Labels: techdebt

#482 Update dependencies
  app/src/main/java/net/squanchy/schedule/view/OtherEventItemView.kt
  app/src/main/java/net/squanchy/service/firebase/FirestoreMappers.kt
  app/src/main/java/net/squanchy/support/view/CardSpacingItemDecorator.kt
  dependencies.gradle
  team-props/git-hooks/pre-commit.sh
  team-props/static-analysis/detekt-config.yml
Labels: devops

#485 Improve filters UI — part 1
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/net/squanchy/schedule/tracksfilter/ScheduleTracksFilter.kt
  app/src/main/java/net/squanchy/support/graphics/Color.kt
  app/src/main/res/drawable/chip_background.xml
  app/src/main/res/drawable/filters_separator.xml
  app/src/main/res/layout/activity_track_filters.xml
  app/src/main/res/layout/track_filters_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/palette.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  dependencies.gradle
Labels: UI/UX polish, techdebt

#487 Use the schedule page position to sort the schedule pages
  .idea/codeStyles/Project.xml
  app/src/main/java/net/squanchy/schedule/ScheduleService.kt
  app/src/test/java/net/squanchy/schedule/FirestoreScheduleServiceTest.kt
Labels: bug

#489 Add Material Components' Chip
  settings.gradle
  support-chip/build.gradle
  support-chip/lint-baseline.xml
  support-chip/src/main/AndroidManifest.xml
  support-chip/src/main/java/android/support/design/animation/AnimationUtils.java
  support-chip/src/main/java/android/support/design/animation/MotionSpec.java
  support-chip/src/main/java/android/support/design/animation/MotionTiming.java
  support-chip/src/main/java/android/support/design/canvas/CanvasCompat.java
  support-chip/src/main/java/android/support/design/chip/Chip.java
  support-chip/src/main/java/android/support/design/chip/ChipDrawable.java
  support-chip/src/main/java/android/support/design/drawable/DrawableUtils.java
  support-chip/src/main/java/android/support/design/internal/ThemeEnforcement.java
  support-chip/src/main/java/android/support/design/internal/ViewUtils.java
  support-chip/src/main/java/android/support/design/resources/MaterialResources.java
  support-chip/src/main/java/android/support/design/resources/TextAppearance.java
  support-chip/src/main/java/android/support/design/ripple/RippleUtils.java
  support-chip/src/main/res/animator/mtrl_chip_state_list_anim.xml
  support-chip/src/main/res/color/mtrl_chip_background_color.xml
  support-chip/src/main/res/color/mtrl_chip_close_icon_tint.xml
  support-chip/src/main/res/color/mtrl_chip_ripple_color.xml
  support-chip/src/main/res/color/mtrl_chip_text_color.xml
  support-chip/src/main/res/drawable/ic_mtrl_chip_checked_black.xml
  support-chip/src/main/res/drawable/ic_mtrl_chip_checked_circle.xml
  support-chip/src/main/res/drawable/ic_mtrl_chip_close_circle.xml
  support-chip/src/main/res/values/attrs-button.xml
  support-chip/src/main/res/values/attrs-internal.xml
  support-chip/src/main/res/values/attrs-theme.xml
  support-chip/src/main/res/values/attrs.xml
  support-chip/src/main/res/values/dimens.xml
  support-chip/src/main/res/values/integers.xml
  support-chip/src/main/res/values/strings.xml
  support-chip/src/main/res/values/styles-chip.xml
  team-props/static-analysis.gradle
Labels: :x: do not merge, UI/UX polish, under the hood

#493 Update Android Gradle Plugin 3.1.0-rc03 -> 3.1.0
  dependencies.gradle
Labels: devops

#494 Login analytics
  app/src/main/java/net/squanchy/SquanchyApplication.kt
  app/src/main/java/net/squanchy/analytics/Analytics.kt
  app/src/main/java/net/squanchy/analytics/AnalyticsModule.kt
  app/src/main/java/net/squanchy/analytics/FirstStartDetector.kt
  app/src/main/java/net/squanchy/analytics/LoginStatus.kt
  app/src/main/java/net/squanchy/eventdetails/EventDetailsActivity.kt
  app/src/main/java/net/squanchy/eventdetails/EventDetailsComponent.kt
  app/src/main/java/net/squanchy/home/HomeActivity.kt
  app/src/main/java/net/squanchy/navigation/Navigator.kt
  app/src/main/java/net/squanchy/onboarding/account/AccountOnboardingActivity.kt
  app/src/main/java/net/squanchy/onboarding/account/AccountOnboardingComponent.kt
  app/src/main/java/net/squanchy/settings/SettingsActivity.kt
  app/src/main/java/net/squanchy/settings/SettingsFragment.kt
  app/src/main/java/net/squanchy/settings/SettingsFragmentComponent.kt
  app/src/main/java/net/squanchy/signin/SignInActivity.kt
  app/src/main/java/net/squanchy/signin/SignInComponent.kt
  app/src/main/java/net/squanchy/signin/SignInOrigin.kt
Labels: epic:analytics

#496 Improve filters UI/MVP chips
  app/src/main/java/net/squanchy/schedule/tracksfilter/ScheduleTracksFilter.kt
  app/src/main/java/net/squanchy/schedule/tracksfilter/widget/FilterChipView.kt
  app/src/main/java/net/squanchy/schedule/view/ScheduleDayPageView.kt
  app/src/main/java/net/squanchy/schedule/view/ScheduleViewPagerAdapter.kt
  app/src/main/java/net/squanchy/support/graphics/Color.kt
  app/src/main/res/drawable/chip_background.xml
  app/src/main/res/layout/track_filters_item.xml
  app/src/main/res/values/attrs_filter_chip_view.xml
  app/src/main/res/values/styles.xml
Labels: UI/UX polish

#497 Add Android KTX dependency
  app/build.gradle
  dependencies.gradle
Labels: devops
